spring:
  application:
    name: warehouseDemo
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: gagulik014A!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8082