spring:
  application:
    name: warehouseDemo
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: gagulik014A!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8082
jwt:
  secret: b10bac_super_secret_key_which_is_long_enough_please_change
  expiration-ms: 86400000
services:
  company-url: http://kinomino.ru/api/company
  attribute-url: http://kinomino.ru/api/attribute
  user-url: http://kinomino.ru/api/users
  #  user-url: http://localhost:8070/api
