package com.biobac.warehouse.entity;

public enum Entities {
    PRODUCT,
    WAREHOUSE,
    RECIPEITEM,
    INGREDIENT,
    INVENTORYITEM,
    INGREDIENTGROUP,
    PRODUCTGROUP,
    WAREHOUSEGROUP,
    INGREDIENTCOMPONENT,
    INGREDIENTHISTORY,
    ATTRIBUTEGROUP,
}
