package com.biobac.warehouse.entity;

public enum Entities {
    PRODUCT,
    WAREHOUSE,
    RECIPEITEM,
    INGREDIENT,
    INVENTORYITEM,
    INGREDIENTGROUP,
    PRODUCTGROUP,
    WAREHOUSEGROUP,
    INGREDIENTCOMPONENT,
    INGREDIENTHISTORY,
    ATTRIBUTEGROUP,

    // Fixed assets module
    ASSET,
    ASSETCATEGORY,
    ASSETSTATUS,
    DEPRECIATIONMETHOD,
    DEPRECIATIONRECORD,
    ASSETIMPROVEMENT,
    DEPARTMENT,
}
